window.purviewConditions = {
    exchange: [
        { base: "Sender is", requiresProp: true, context: "both" },
        { base: "The sender is a member of", requiresProp: true, context: "both" },
        { base: "Sender IP address is", requiresProp: true, context: "server" },
        { base: "Sender address contains words", requiresProp: true, context: "server" },
        { base: "Sender address matches patterns", requiresProp: true, context: "server" },
        { base: "Sender domain is", requiresProp: true, context: "both" },
        { base: "Sender scope", requiresProp: true, context: "server" },
        { base: "Sender's specified properties include words", requiresProp: true, context: "server" },
        { base: "Sender's specified properties match patterns", requiresProp: true, context: "server" },
        { base: "Recipient is", requiresProp: true, context: "both" },
        { base: "Recipient domain is", requiresProp: true, context: "both" },
        { base: "Recipient address contains words", requiresProp: true, context: "server" },
        { base: "Recipient address matches patterns", requiresProp: true, context: "server" },
        { base: "Sent to member of", requiresProp: true, context: "both" },
        { base: "Recipient's specified properties include words", requiresProp: true, context: "server" },
        { base: "Recipient's specified properties match patterns", requiresProp: true, context: "server" },
        { base: "Recipient scope/Content is shared with", requiresProp: true, context: "both" },
        { base: "Unique recipient count over", requiresProp: true, context: "server" },
        { base: "Unique recipient domain over", requiresProp: true, context: "server" },
        { base: "Subject contains words or phrases", requiresProp: true, context: "both" },
        { base: "Subject matches patterns", requiresProp: true, context: "server" },
        { base: "Content contains", requiresProp: true, context: "both" },
        { base: "Content is not labeled", requiresProp: false, context: "both" },
        { base: "Subject or Body matches pattern", requiresProp: true, context: "server" },
        { base: "Subject or Body contains words", requiresProp: true, context: "server" },
        { base: "Attachment is password protected", requiresProp: false, context: "server" },
        { base: "Attachment's file extension is", requiresProp: true, context: "both" },
        { base: "Any email attachment's content could not be scanned", requiresProp: false, context: "server" },
        { base: "Any email attachment's content didn't complete scanning", requiresProp: false, context: "server" },
        { base: "Document scan failures", requiresProp: false, context: "server" },
        { base: "Document name contains words", requiresProp: true, context: "server" },
        { base: "Document name matches patterns", requiresProp: true, context: "server" },
        { base: "Document property is", requiresProp: true, context: "server" },
        { base: "Document size equals or is greater than", requiresProp: true, context: "server" },
        { base: "Any attachment's content includes words", requiresProp: true, context: "server" },
        { base: "Any attachment's content matches patterns", requiresProp: true, context: "server" },
        { base: "Header contains words or phrases", requiresProp: true, context: "server" },
        { base: "Header matches patterns", requiresProp: true, context: "server" },
        { base: "With importance", requiresProp: true, context: "server" },
        { base: "Content character set contains words", requiresProp: true, context: "server" },
        { base: "Has sender override", requiresProp: false, context: "server" },
        { base: "Message type matches", requiresProp: true, context: "server" },
        { base: "The message size is greater than or equal to", requiresProp: true, context: "server" }
    ],
    endpoint: [
        { base: "Content contains", requiresProp: true },
        { base: "Insider risk level for Adaptive Protection is", requiresProp: true },
        { base: "Content is not labeled", requiresProp: false },
        { base: "Document property is", requiresProp: true },
        { base: "Document could not be scanned", requiresProp: false },
        { base: "Document or attachment is password protected", requiresProp: false },
        { base: "Document didn't complete scanning", requiresProp: false },
        { base: "File type is", requiresProp: true },
        { base: "File extension is", requiresProp: true },
        { base: "The user access a sensitive site from Edge", requiresProp: false },
        { base: "Document name contains words or phrases", requiresProp: true },
        { base: "Document name matches patterns", requiresProp: true },
        { base: "Document size equals or is greater than", requiresProp: true },
        { base: "File created by a restricted app", requiresProp: true },
        { base: "File downloaded from", requiresProp: true }
    ],
    sharepoint: [
        { base: "Content contains", requiresProp: true },
        { base: "Content is not labeled", requiresProp: false },
        { base: "Document property is", requiresProp: true },
        { base: "Document name contains words", requiresProp: true },
        { base: "Document name matches patterns", requiresProp: true },
        { base: "Document size equals or is greater than", requiresProp: true },
        { base: "Document could not be scanned", requiresProp: false },
        { base: "Document didn't complete scanning", requiresProp: false },
        { base: "Attachment's file extension is", requiresProp: true },
        { base: "Document is password protected", requiresProp: false },
        { base: "Recipient scope/Content is shared with", requiresProp: true },
        { base: "Created by", requiresProp: true },
        { base: "Last modified by", requiresProp: true },
        { base: "Site URL contains words", requiresProp: true },
        { base: "Site URL matches patterns", requiresProp: true }
    ],
    teams: [
        { base: "Content contains", requiresProp: true },
        { base: "Content is not labeled", requiresProp: false },
        { base: "Sender is", requiresProp: true },
        { base: "Sender domain is", requiresProp: true },
        { base: "Recipient is", requiresProp: true },
        { base: "Recipient domain is", requiresProp: true },
        { base: "The sender is a member of", requiresProp: true },
        { base: "Sent to member of", requiresProp: true },
        { base: "Message type matches", requiresProp: true },
        { base: "Sender scope", requiresProp: true }
    ]
};

window.psPropertyMap = {
    "ContentContainsSensitiveInformation": "Content contains",
    "SenderDomainIs": "Sender domain is",
    "SentTo": "Recipient is",
    "DocumentIsPasswordProtected": "Attachment is password protected",
    "ContentExtensionMatchesWords": "Attachment's file extension is",
    "SubjectContainsWords": "Subject contains words or phrases",
    "SubjectOrBodyContainsWords": "Subject or Body contains words",
    "AnyOfRecipientAddressMatchesPatterns": "Recipient address matches patterns",
    "FromScope": "Sender scope",
    "AccessScope": "Recipient scope/Content is shared with",
    "RecipientDomainIs": "Recipient domain is",
    "SubjectMatchesPatterns": "Subject matches patterns",
    "SubjectOrBodyMatchesPatterns": "Subject or Body matches pattern",
    "ContentIsNotLabeled": "Content is not labeled",
    "MessageIsNotLabeled": "Content is not labeled",
    "AttachmentIsNotLabeled": "Content is not labeled",
    "DocumentMatchesPatterns": "Document name matches patterns",
    "DocumentContainsWords": "Document name contains words",
    "MessageSizeOver": "The message size is greater than or equal to",
    "DocumentSizeOver": "Document size equals or is greater than",
    "From": "Sender is",
    "FromMemberOf": "The sender is a member of",
    "SentToMemberOf": "Sent to member of",
    "AnyOfRecipientAddressContainsWords": "Recipient address contains words",
    "FromAddressMatchesPatterns": "Sender address matches patterns",
    "FromAddressContainsWords": "Sender address contains words",
    "SenderIPRanges": "Sender IP address is",
    "ContentCharacterSetContainsWords": "Content character set contains words",
    "HasSenderOverride": "Has sender override",
    "MessageTypeMatches": "Message type matches",
    "HeaderContainsWords": "Header contains words or phrases",
    "HeaderMatchesPatterns": "Header matches patterns",
    "ContentIsShared": "Recipient scope/Content is shared with",
    // SharePoint / OneDrive
    "SharedWith": "Recipient scope/Content is shared with",
    "CreatedBy": "Created by",
    "ModifiedBy": "Last modified by",
    "SPContentContainsSensitiveInformation": "Content contains",
    "SPDocumentIsPasswordProtected": "Document is password protected",
    "SPDocumentSizeOver": "Document size equals or is greater than",
    "SPDocumentNameContainsWords": "Document name contains words",
    "SPDocumentNameMatchesPatterns": "Document name matches patterns",
    "SPDocumentPropertyEquals": "Document property is",
    "SPDocumentCouldNotBeScanned": "Document could not be scanned",
    "SiteURLContainsWords": "Site URL contains words",
    "SiteURLMatchesPatterns": "Site URL matches patterns",
    // Teams
    "TeamsMessageMemberOf": "Sent to member of",
    "TeamsMessageSenderDomain": "Sender domain is",
    "TeamsMessageRecipientDomain": "Recipient domain is"
};

window.getConditionContext = function(base) {
    const ex = purviewConditions.exchange.find(c => c.base === base);
    if (ex && ex.context) return ex.context;
    return 'server';
};

window.renderContextBadge = function(context) {
    if (context === 'both') {
        return `<span class="bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-300 text-[10px] px-1.5 py-0.5 rounded font-bold uppercase ml-2 shadow-sm">Client+Server</span>`;
    } else {
        return `<span class="bg-purple-100 dark:bg-purple-900/30 text-purple-800 dark:text-purple-300 text-[10px] px-1.5 py-0.5 rounded font-bold uppercase ml-2 shadow-sm">Server-only</span>`;
    }
};
