window.purviewConditions = {
    exchange: [
        { base: "Sender is", requiresProp: true },
        { base: "The sender is a member of", requiresProp: true },
        { base: "Sender IP address is", requiresProp: true },
        { base: "Sender address contains words", requiresProp: true },
        { base: "Sender address matches patterns", requiresProp: true },
        { base: "Sender domain is", requiresProp: true },
        { base: "Sender scope", requiresProp: true },
        { base: "Sender's specified properties include words", requiresProp: true },
        { base: "Sender's specified properties match patterns", requiresProp: true },
        { base: "Recipient is", requiresProp: true },
        { base: "Recipient domain is", requiresProp: true },
        { base: "Recipient address contains words", requiresProp: true },
        { base: "Recipient address matches patterns", requiresProp: true },
        { base: "Sent to member of", requiresProp: true },
        { base: "Recipient's specified properties include words", requiresProp: true },
        { base: "Recipient's specified properties match patterns", requiresProp: true },
        { base: "Recipient scope/Content is shared with", requiresProp: true },
        { base: "Unique recipient count over", requiresProp: true },
        { base: "Unique recipient domain over", requiresProp: true },
        { base: "Subject contains words or phrases", requiresProp: true },
        { base: "Subject matches patterns", requiresProp: true },
        { base: "Content contains", requiresProp: true },
        { base: "Content is not labeled", requiresProp: false },
        { base: "Subject or Body matches pattern", requiresProp: true },
        { base: "Subject or Body contains words", requiresProp: true },
        { base: "Attachment is password protected", requiresProp: false },
        { base: "Attachment's file extension is", requiresProp: true },
        { base: "Any email attachment's content could not be scanned", requiresProp: false },
        { base: "Any email attachment's content didn't complete scanning", requiresProp: false },
        { base: "Document scan failures", requiresProp: false },
        { base: "Document name contains words", requiresProp: true },
        { base: "Document name matches patterns", requiresProp: true },
        { base: "Document property is", requiresProp: true },
        { base: "Document size equals or is greater than", requiresProp: true },
        { base: "Any attachment's content includes words", requiresProp: true },
        { base: "Any attachment's content matches patterns", requiresProp: true },
        { base: "Header contains words or phrases", requiresProp: true },
        { base: "Header matches patterns", requiresProp: true },
        { base: "With importance", requiresProp: true },
        { base: "Content character set contains words", requiresProp: true },
        { base: "Has sender override", requiresProp: false },
        { base: "Message type matches", requiresProp: true },
        { base: "The message size is greater than or equal to", requiresProp: true }
    ],
    endpoint: [
        { base: "Content contains", requiresProp: true },
        { base: "Insider risk level for Adaptive Protection is", requiresProp: true },
        { base: "Content is not labeled", requiresProp: false },
        { base: "Document property is", requiresProp: true },
        { base: "Document could not be scanned", requiresProp: false },
        { base: "Document or attachment is password protected", requiresProp: false },
        { base: "Document didn't complete scanning", requiresProp: false },
        { base: "File type is", requiresProp: true },
        { base: "File extension is", requiresProp: true },
        { base: "The user access a sensitive site from Edge", requiresProp: false },
        { base: "Document name contains words or phrases", requiresProp: true },
        { base: "Document name matches patterns", requiresProp: true },
        { base: "Document size equals or is greater than", requiresProp: true },
        { base: "File created by a restricted app", requiresProp: true },
        { base: "File downloaded from", requiresProp: true }
    ]
};

window.psPropertyMap = {
    "ContentContainsSensitiveInformation": "Content contains",
    "SenderDomainIs": "Sender domain is",
    "SentTo": "Recipient is",
    "DocumentIsPasswordProtected": "Attachment is password protected",
    "ContentExtensionMatchesWords": "Attachment's file extension is",
    "SubjectContainsWords": "Subject contains words or phrases",
    "SubjectOrBodyContainsWords": "Subject or Body contains words",
    "AnyOfRecipientAddressMatchesPatterns": "Recipient address matches patterns",
    "FromScope": "Sender scope",
    "AccessScope": "Recipient scope/Content is shared with"
};
